const FIXED_DELTA_TIME_MS = 1000 / 60;

export const CONFIG = {
  width: 1000,
  height: 600,
  groundY: 500,

  cannonX: 500,
  cannonBaseRadius: 44,
  cannonBarrelLength: 88,
  cannonBarrelThickness: 16,
  cannonFootprintHalfWidth: 44,
  cannonTurnSpeedDegPerSecond: 140,
  cannonMinAngleDeg: 10,
  cannonMaxAngleDeg: 170,
  cannonInitialAngleDeg: 90,
  startingNukes: 3,
  laserCooldownMs: FIXED_DELTA_TIME_MS,
  laserVisibleFrames: 1,
  laserStrokeWidth: 4,
  asteroidSpawnIntervalMs: 1800,
  asteroidMinValue: 1,
  asteroidMaxValue: 4,
  asteroidRadiusBase: 10,
  asteroidRadiusScale: 8,
  asteroidVelocityXMin: -40,
  asteroidVelocityXMax: 40,
  asteroidVelocityYMin: 55,
  asteroidVelocityYMax: 80,
  asteroidSplitSpeedMultiplier: 1.08,
  asteroidSplitAngleJitterDeg: 28,
  asteroidStartX: 420,
  asteroidStartY: 80,
  asteroidSpawnMinX: 120,
  asteroidSpawnMaxX: 880,
  buildingCountPerSide: 4,
  buildingWidth: 54,
  buildingGap: 18,
  buildingMinHeight: 44,
  buildingMaxHeight: 110,
  buildingSidePadding: 54,
  cannonClearHalfWidth: 86,

  fixedDeltaTimeMs: FIXED_DELTA_TIME_MS
} as const;
